version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  redis:
    image: redis
    ports:
        - "6379:6379"
  php: 
    image: php:7-fpm
    volumes:
      - ./code:/code
  db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
